name: poke_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.5
  sqflite: ^2.0.3+1
  path: ^1.8.1
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
